<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <title>Comments &laquo; Admin</title>
  <link rel="stylesheet" href="/static/assets/vendors/bootstrap/css/bootstrap.css">
  <link rel="stylesheet" href="/static/assets/vendors/font-awesome/css/font-awesome.css">
  <link rel="stylesheet" href="/static/assets/vendors/nprogress/nprogress.css">
  <link rel="stylesheet" href="/static/assets/css/admin.css">
  <script src="/static/assets/vendors/nprogress/nprogress.js"></script>
</head>
<style>
  .loading {
    display: flex;
    align-items: center;
    justify-content: center;
    position: fixed;
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
    background-color: rgba(175,175,224,.15);
    z-index: 999;
    
  }
</style>

<style type="text/css">
  @keyframes ldio-8c7a0wit2jf {
    0% { transform: rotate(0) }
    100% { transform: rotate(360deg) }
  }
  .ldio-8c7a0wit2jf div { box-sizing: border-box!important }
  .ldio-8c7a0wit2jf > div {
    position: absolute;
    width: 144px;
    height: 144px;
    top: 28px;
    left: 28px;
    border-radius: 50%;
    border: 16px solid #000;
    border-color: #47617a transparent #47617a transparent;
    animation: ldio-8c7a0wit2jf 0.8474576271186439s linear infinite;
  }
  .ldio-8c7a0wit2jf > div:nth-child(2) { border-color: transparent }
  .ldio-8c7a0wit2jf > div:nth-child(2) div {
    position: absolute;
    width: 100%;
    height: 100%;
    transform: rotate(45deg);
  }
  .ldio-8c7a0wit2jf > div:nth-child(2) div:before, .ldio-8c7a0wit2jf > div:nth-child(2) div:after { 
    content: "";
    display: block;
    position: absolute;
    width: 16px;
    height: 16px;
    top: -16px;
    left: 48px;
    background: #47617a;
    border-radius: 50%;
    box-shadow: 0 128px 0 0 #47617a;
  }
  .ldio-8c7a0wit2jf > div:nth-child(2) div:after { 
    left: -16px;
    top: 48px;
    box-shadow: 128px 0 0 0 #47617a;
  }
  .loadingio-spinner-dual-ring-zma9aq9mif {
    width: 200px;
    height: 200px;
    display: inline-block;
    overflow: hidden;
    background: #f1f2f3;
  }
  .ldio-8c7a0wit2jf {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-8c7a0wit2jf div { box-sizing: content-box; }
  /* generated by https://loading.io/ */
</style>
<body>

  
  <div class="main">
     <?php include 'inc/navbar.php'; ?>
     
    <div class="container-fluid">
      <div class="page-title">
        <h1>所有评论</h1>
      </div>
      <!-- 有错误信息时展示 -->
      <!-- <div class="alert alert-danger">
        <strong>错误！</strong>发生XXX错误
      </div> -->
      <div class="page-action">
        <!-- show when multiple checked -->
        <div class="btn-batch" style="display: none">
          <button class="btn btn-info btn-sm">批量批准</button>
          <button class="btn btn-warning btn-sm">批量拒绝</button>
          <button class="btn btn-danger btn-sm">批量删除</button>
        </div>
        <ul class="pagination pagination-sm pull-right">
          
        </ul>
      </div>
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th class="text-center" width="40"><input type="checkbox"></th>
            <th>作者</th>
            <th>评论</th>
            <th>评论在</th>
            <th>提交于</th>
            <th>状态</th>
            <th class="text-center" width="150">操作</th>
          </tr>
        </thead>
        <tbody id="tb">
          
          <!-- 模板填充 -->
        </tbody>
      </table>
    </div>
  </div>
<div class="loading" style="display: none;">
  <div class="loadingio-spinner-dual-ring-zma9aq9mif"><div class="ldio-8c7a0wit2jf">
  <div></div><div><div></div></div>
  </div></div>

</div>

  <?php $current_page = 'comments'; ?>
  <?php include 'inc/silderbar.php'; ?>

  <script src="/static/assets/vendors/jquery/jquery.js"></script>
  <script src="/static/assets/vendors/bootstrap/js/bootstrap.js"></script>
  <script src="/static/assets/vendors/jsrender/jsrender.js"></script>
  <script src="/static/assets/vendors/twbs-pagination/jquery.twbsPagination.js"></script>
  <script>
    $(document)
    .ajaxStart(function(){

      $('.loading').fadeIn();

      NProgress.start();
    })
    .ajaxStop(function(){
      $('.loading').fadeOut();

      NProgress.done()
    });

  </script>

  <script id="comments-tmpl" type="text/x-jsrender">
    {{for comments}}
      <tr {{if status== 'held'}} class="warning"{{else status == 'rejected'}} class="danger" {{/if}} data-id="{{:id}}">
            <td class="text-center"><input type="checkbox"></td>
            <td>{{:author}}</td>
            <td>{{:content}}</td>
            <td>{{:post_title}} </td>
            <td>{{:created}}/10/07</td>
            <td>{{:status}}</td>
            <td class="text-center">
            {{if status == 'held'}}
              <a href="post-add.html" class="btn btn-info btn-xs">批准</a>
              <a href="post-add.html" class="btn btn-warning btn-xs">批准</a>
            {{/if}}
              <a href="javascript:;" class="btn btn-danger btn-xs btn-delete">删除</a>
            
            </td>
          </tr>
    {{/for}}
  </script>
  <script>
    //发送ajax请求，获取所需列表数据
    // $.getJSON(请求的地址，请求的传过去的参数，回调函数)
    let tb = $('#tb');
    var current_page = 1;
    function loadPageData(page){
  
      tb.fadeOut();

      $.getJSON('/admin/api/comments.php', {page : page}, function(res){  
        if(page > res.totalPages){
          loadPageData(res.totalPages)
          return
        }


        $('.pagination').twbsPagination('destroy');
        $('.pagination').twbsPagination({
          first:'&laquo;',
          last:'&raquo;',
          prev:'上一页',
          next: '下一页',
          startPage: page,
          totalPages : res.totalPages,
          visiablePages: 5,
          initiateStartPageClick: false,
          onPageClick: function(e, page){
            loadPageData(page);
           
          }
      })
       // console.log(res);
       var html = $("#comments-tmpl").render({
        comments : res.comments
       });

       tb.html(html).fadeIn();
       current_page = page;
      });
    }

    loadPageData(1);

    //===========删除功能==========
    // $('.btn-delete').on('click', '', function(){
        //由于按钮是动态添加的，点击事件无法添加
    // });
     
    /*需要通过委托事件*/
    $('#tb').on('click','.btn-delete',function(){
        // console.log(111);
      //获取当前的tr
      var tr = $(this).parent().parent();
      //获取trDOM的中的自定义元素
      
      var id =  tr.data('id');

      $.get('/admin/api/comments-delete.php', {id : id}, function(res){  //回调函数
          if(!res) return;
          // tr.remove();
          // 重新载入当前页面，再次发送ajax请求
          loadPageData(current_page);
          
      });

    });
  </script>
</body>
</html>
